apiVersion: apps/v1
kind: Deployment
metadata:
    name: gamutkart-prod-deploy
    labels:
      app: gamutkart
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gamutkart
  template:
    metadata:
      labels:
        app: gamutkart
    spec:
      containers:
        - name: nginx-container
          image: surya123789/my_own_project:latest
          ports:
          - containerPort: 80
          
---


apiVersion: apps/v1
kind: Service
metadata:
    name: gamutkart-prod-service
    labels:
      app: gamutkart-prod-service
spec:
  selector:
    app: gamutkart
  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
